Feature/size limited memfile names
eclipse-ecal/ecal pull request #1009
Opened 2023-03-10 18:15 UTC by KerstinKeller

**Pull request type**

With this PR, ecal memory files / events will be limited to max 25 characters

`ecal_<topic&time_hash>` as a base name, and then possibly `_ack` as well as process specific events for synchronization.

```
ecal_        5 char
<hash>       8 char
_            1 char
<PID>    max 7 char
_ack         4 char
```

This totally works and communication works fine, there is no kind of incompatibility.

However, we should reiterate on what really makes sense here.
After all we want to avoid collisions. To avoid collisions, all we really need for the filename would be the creation time, it's not even necessary to include the topic name.

Also if we think about possibly taking out the shared memory as a separate library, we'd probably want to keep being able to set a file name, and not have the library compute some random hashes.

2023-03-10 18:16 UTC, KerstinKeller commented
@JerryHyun  FYI

2023-03-13 07:08 UTC, FlorianReimold commented
@KerstinKeller: Very good overview of the names along with the used-up characters, but you forgot the `_evt`, which takes up 4 more characters and gets us to 29 out of 31 in total :)

2023-03-15 10:40 UTC, KerstinKeller commented on ecal/core/src/io/ecal_memfile_naming.cpp
> +#include <io/ecal_memfile_naming.h>
License header missing!!!!!

2023-03-15 10:46 UTC, KerstinKeller reviewed
`CSyncMemoryFile` should keep base_name, which can be `ecal_` and passed from outside, which be used in `BuildRandomMemFileName`.

2023-03-16 15:27 UTC, FlorianReimold requested changes
Looks good, besides the license header and the numeric_limits change 😉

2023-03-16 15:27 UTC, FlorianReimold commented on ecal/core/src/io/ecal_memfile_naming.cpp
> +      static std::uniform_int_distribution<uint32_t> dist(0, UINT32_MAX);
```suggestion
      static std::uniform_int_distribution<uint32_t> dist(0, std::numeric_limits<uint32_t>::max());
```

2023-03-16 15:27 UTC, FlorianReimold commented on ecal/core/src/io/ecal_memfile_naming.cpp
> +#include <random>
```suggestion
#include <random>
#include <limits>
```

2023-03-20 10:37 UTC, hannemn commented on ecal/core/src/io/ecal_memfile_naming.cpp
> +      static std::random_device rd;
Doesn't the random device requires a seed value?

2023-03-20 10:45 UTC, KerstinKeller commented on ecal/core/src/io/ecal_memfile_naming.cpp
> +      static std::random_device rd;
No, that's the point of the random device, that it is truly random. It's somehow connected to the hardware.

2023-03-20 13:16 UTC, merged

2023-03-20 18:52 UTC, hannemn commented on ecal/core/src/io/ecal_memfile_naming.cpp
> +      static std::random_device rd;
I see, but it seems to be at least implementation specific. Cpp reference remarks: "[...]std::random_device may be implemented in terms of an implementation-defined pseudo-random number engine if a non-deterministic source (e.g. a hardware device) is not available to the implementation. In this case each std::random_device object may generate the same number sequence. [...]"