ecal util gettopics/getservices logic fixed
eclipse-ecal/ecal pull request #1010
Opened 2023-03-13 18:26 UTC by rex-schilasky

**Pull request type**

Please check the type of change your PR introduces:
- [X] Bugfix

**What is the current behavior?**
Process internal topics / services were not been updated in the descgate internal maps and external topics / services kept internal ones with the same topic name or service/method name alive.

**What is the new behavior?**
* registration provider updates internal descgate entities (topics / services) and prevents expiration
* topic/service description quality logic cleaned up, descriptions of expired topics/services can be overwritten by matching new entities, even they have the same or a lower quality
* unit tests improved/added for GetTopics and GetServices API's

2023-03-28 11:15 UTC, hannemn commented on ecal/core/src/service/ecal_clientgate.cpp
> +    for (auto method : ecal_sample_service.methods())
I guess you might be able to iterate with const auto& here, right?

2023-04-03 16:05 UTC, FlorianReimold requested changes
Only found some nice-to-have changes. nothing critical

2023-04-03 16:05 UTC, FlorianReimold commented on ecal/core/src/ecal_registration_provider.cpp
> +      auto& ecal_sample_service = iter->second.service();
I guess this can be made const? please double check

```suggestion
      const auto& ecal_sample_service = iter->second.service();
```

2023-04-03 16:05 UTC, FlorianReimold commented on ecal/core/src/ecal_registration_provider.cpp
> +      for (auto method : ecal_sample_service.methods())
I guess this can be made a const reference? Please double check.

```suggestion
      for (const auto& method : ecal_sample_service.methods())
```

2023-04-03 16:05 UTC, FlorianReimold commented on ecal/core/src/ecal_registration_provider.cpp
> +      std::string topic_name(iter->second.topic().tname());
These can all be made const

2023-04-05 12:27 UTC, FlorianReimold approved these changes

2023-04-05 14:13 UTC, merged