Add CapnProto Publisher and Subscriber to Python API
eclipse-ecal/ecal pull request #1089
Opened 2023-05-04 16:37 UTC by CruxDevStuff

**Pull request type**

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

**What is the new behavior?**

- Subscribe to CapnProto Messages from Python
- Publish CapnProto Messages from Python

**Does this introduce a breaking change?**

- [ ] Yes
- [X] No

2023-05-07 10:15 UTC, CruxDevStuff commented
> Thank you @CruxDevStuff for contributing ! We will check this next week. If you have python samples for sending and receiving capnproto messages like those [ones](https://github.com/eclipse-ecal/ecal/tree/master/samples/cpp/pubsub/capnp) in cpp, it would be great too.

I've added an [Example](https://github.com/CruxDevStuff/ecal/tree/master/samples/python/capnp)

2023-05-07 11:04 UTC, rex-schilasky commented
> > Thank you @CruxDevStuff for contributing ! We will check this next week. If you have python samples for sending and receiving capnproto messages like those [ones](https://github.com/eclipse-ecal/ecal/tree/master/samples/cpp/pubsub/capnp) in cpp, it would be great too.
> 
> 
> 
> I've added an [Example](https://github.com/CruxDevStuff/ecal/tree/master/samples/python/capnp)

Great. Thank you.

2023-05-08 11:12 UTC, rex-schilasky commented
@CruxDevStuff can you please create an [eclipse account](https://accounts.eclipse.org/user/login?destination=legal/eca/validation/153175), then we can merger your PR after the review has  been done.

2023-06-06 13:04 UTC, KerstinKeller requested changes
Hi, sorry for the long wait.
Thanks for making this contribution, however I do have a few remarks:

- Dependencies: we now have a dependency to `pycapnp`, it needs to be added to requirements.txt for ecal.
- Before running the samples, the user will have to run the capnproto compiler on the schema file themselves. I'd prefer if we'd check in the generated code here as we do in the protobuf case. Or, alternatively, have a way to generate this on python import? At least it should be in the README.md

2023-06-06 13:04 UTC, KerstinKeller commented on samples/python/capnp/messages.capnp
> +@0xb6249c5df1f7e512;
can you use the same message like is used for the c++ samples? this way we can communicate the samples with python send / c++ receive and vice versa.

2025-01-07 10:27 UTC, Peguen commented
In the course of changing the Python API and bindings during 6.x release, this functionality will be implemented.

2025-01-07 10:27 UTC, closed without merging