feat: add package.xml
eclipse-ecal/ecal pull request #1124
Opened 2023-06-10 18:03 UTC by wep21

**Pull request type**

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): add package.xml to be recognized as a ros package suggested [here](https://github.com/eclipse-ecal/rmw_ecal/pull/61#issuecomment-1550505782)

**What is the current behavior?**

Issue Number: N/A

**What is the new behavior?**

-
-
-

**Does this introduce a breaking change?**

- [ ] Yes
- [ ] No

**Other information**

2023-06-12 11:25 UTC, FlorianReimold commented
Please tell us anything about this PR, e.g. what that file is good for.

2023-06-12 11:38 UTC, FlorianReimold commented on package.xml
> +    <version>5.11.4</version>
Is there any way to make this variable? For instance making it check git tags, creating this file with cmake etc.
This PR is to master, so this defnitively is NOT 5.11.4. It's more like a 5.12 alpha. Also, maintaining version numbers that are scattered across files is always a pain

2023-06-12 11:38 UTC, FlorianReimold commented on package.xml
> +    <depend>qtbase5-dev</depend>
Where did this list come from?
- libecal_core.so / ecal_core.dll does not need hdf5. That is only needed for the recording and replay tools
- libqwt-qt5-dev is only needed for building 1 specific eCAL Mon Plugin. Is it the goal to build all the tools, too?
- If all the tools are meant to be built as well, the dependency list will likely be much longer

2023-06-12 11:38 UTC, FlorianReimold commented on package.xml
> +        <build_type>cmake</build_type>
I don't know much about the package.xml, but does it contain information on how to actually build the lib? Like CMake options / a command line?

2023-06-13 02:01 UTC, wep21 commented on package.xml
> +    <depend>qtbase5-dev</depend>
In ros build farm, a build job is executed without any options, so I added the libraries which is necessary to build successfully without any options.

2023-06-13 02:05 UTC, wep21 commented on package.xml
> +        <build_type>cmake</build_type>
No, we need to specify options via `colcon` or `cmake` or write them in CMakeLists.txt directly. `package.xml`  doesn't contain the information.

2023-06-13 02:13 UTC, wep21 commented on package.xml
> +    <version>5.11.4</version>
> Is there any way to make this variable? For instance making it check git tags, creating this file with cmake etc.

I'm sorry, but I don't have any idea to do so. I usually update version in `package.xml` and add git tag at the same time via command line tool named [catkin_preprare_release](http://wiki.ros.org/bloom/Tutorials/ReleaseCatkinPackage).

2023-06-13 08:58 UTC, FlorianReimold commented on package.xml
> +    <depend>qtbase5-dev</depend>
Hm, not being able to specify cmake options doesn't sound optimal at all. Here is a list of dependencies that I pulled from the source package of our PPA (Jammy). All of them should be required for default build on Ubuntu 22.04.

```qtbase5-dev (>= 5.9), libqwt-qt5-dev (>= 6.1), libhdf5-dev, libprotobuf-dev (>= 3.0), libprotoc-dev (>= 3.0), protobuf-compiler (>= 3.0), libcurl4-openssl-dev, libyaml-cpp-dev```

2023-06-13 17:19 UTC, KerstinKeller commented
It seems that this is what a `colcon.pkg` file is for?
This is an examplary file https://github.com/eProsima/Micro-CDR/blob/1c712a08cf5571af0435bf1d881075e813c09513/colcon.pkg#L5,  also see this discussion https://github.com/colcon/colcon.readthedocs.org/issues/44

As Florian said, building all of eCAL is probably not what is needed in the ROS context. eCAL has a lot of options (and what we consider a "default" package, might entirely not be what is useful in the ROS context).

2023-06-13 18:17 UTC, wep21 commented
@KerstinKeller cc @FlorianReimold
Thank you for your comment. I added `colcon.pkg` to build minimal libraries and remove some dependencies from `package.xml`.

2023-06-13 18:48 UTC, wep21 commented on package.xml
> +    <depend>qtbase5-dev</depend>
The system dependencies in package.xml is mainly defined [here](https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml).
These dependecies are for some linux distros, but I guess we can also define another platform dependencies like [this](https://github.com/ros/rosdistro/blob/master/rosdep/osx-homebrew.yaml).

2023-06-16 06:22 UTC, FlorianReimold requested changes
Could you still correct the version number? The current version of the master branch is `5.12.0-nightly2`

2023-06-17 16:49 UTC, wep21 commented
@FlorianReimold I changed the version to `5.12.0-nightly2`, but the version in package.xml should be in the pattern `(0|[1-9][0-9]*)(.(0|[1-9][0-9]*)){2}`, so I would like you to update the version in package.xml to satisfy the pattern when you create a new stable version tag.

2023-06-19 05:53 UTC, FlorianReimold commented
Hm, maybe then just have `5.12.0`? I am just trying to not make people think that the master branch would represent any 5.11 release. For releases, we always create support branches like `support/v5.11`, where we maintain an ABI compatible release. After we have created a new support branch, we then increase the version on our master branch to a new nightly version, so if we create a new `support/v5.12` branch, we will then tag the master `v5.13.0-nightly`, so you directly see that you are in fact **not** using a 5.12 compatible release, if you are working on master. On the 5.12 branche we will then create a release candidate and later the final release, which is then just tagged `v5.12.0`.

Sad to see, that the package xml does not support semantic versioning pre-release identifiers, but maybe it is then better to directly increase the version number to the next minor version (5.12.0 in this case)?

2023-06-29 13:28 UTC, FlorianReimold approved these changes

2023-06-29 13:28 UTC, merged