eCAL::Measurement: New methods
eclipse-ecal/ecal pull request #1232
Opened 2023-10-27 11:23 UTC by KerstinKeller

### Description
Atomic operation for getting / setting datatype information

### Related issues
Preparation for #1076

2023-10-27 11:26 UTC, KerstinKeller commented
@FlorianReimold please review carefully changes regarding eCAL Rec. Both commits can be reviewed separately, too, this decreases the complexity of the review.

2023-10-30 11:31 UTC, FlorianReimold requested changes
I carefully reviewed the eCAL Rec part. Currently, I think the implementation would break the descriptor database, as the encoding is not used in it anymore. Therefore, `std + string` and `proto + string` would be treated equally and overwrite each others descriptors. We need to make sure, that we treat the encoding and typename as atomic pair and never use one part without the other. So basically as it was before.

2023-10-30 11:31 UTC, FlorianReimold commented on app/rec/rec_client_core/src/monitoring_thread.cpp
> +                type_descriptor_map.emplace(topic_info.name, std::make_pair(quality_for_other_channels, topic_info));
Again, now when we have the encoding and type separated, we have to actively make sure, that they are treated as an atomic pair that doesn't behave separated.

The descriptor must always be asigned to a encoding + typename pair.

I also don't see how storing the topic_info instead of just the descriptor string provides a benefit here.

2023-10-30 11:31 UTC, FlorianReimold commented on app/rec/rec_client_core/src/monitoring_thread.cpp
> +            if (!topic_info_map_entry.second.tinfo_.name.empty())
Again, now when we have the encoding and type separated, we have to actively make sure, that they are treated as an atomic pair that doesn't behave separated.

2023-10-30 11:31 UTC, FlorianReimold commented on app/rec/rec_client_core/src/monitoring_thread.cpp
> +              auto type_descriptor_entry_it = type_descriptor_map.find(topic_info_map_entry.second.tinfo_.name);
Again, now when we have the encoding and type separated, we have to actively make sure, that they are treated as an atomic pair that doesn't behave separated.

2023-10-30 13:39 UTC, KerstinKeller commented on contrib/ecalhdf5/include/ecalhdf5/eh5_writer.h
> +      * To be removed soon-ish
It will be removed before we release, but as of now I could just split again`eh5_writer.h` in implementation & header, so creating a `cpp` file, and moving it over there.

2023-10-30 14:07 UTC, FlorianReimold commented on app/rec/rec_client_core/src/monitoring_thread.cpp
> +            if (!topic_info.name.empty())
Well yeah, ok, but not even treating encoding and typename as an atomic pair seems to head in the different direction. The goal of this code is to enrich the measurement with a descriptor, even though it may not be sent by some node.

2023-10-30 14:07 UTC, KerstinKeller commented on app/rec/rec_client_core/src/monitoring_thread.cpp
> +          std::map<std::string, std::pair<int, eCAL::SDataTypeInformation>> type_descriptor_map;    // Type        -> DatatypeInformation           (used for topics that we know the type of, but have
For the second point, yes I know it now holds redundant information, but it's easier to use, as you can just extract the datatype information.

The whole point of this PR is to treat all this info (SDatatypeInformation) as atomic.
Btw, is this even a valid usecase: typename but no descriptor? Or descriptor is updated after typename?
To be honest, I don't think it is. So maybe we can even get rid of the second map?

2023-10-30 14:16 UTC, FlorianReimold commented on app/rec/rec_client_core/src/monitoring_thread.cpp
> +          std::map<std::string, std::pair<int, eCAL::SDataTypeInformation>> type_descriptor_map;    // Type        -> DatatypeInformation           (used for topics that we know the type of, but have
The reason is, that there may be user code that doesn't send descriptor information. So I know the type of a topic, but don't have a descriptor. Another node may however publish, so I take it from there. A second use case is that there may be multiple different descriptor sent for the same type, e.g. from the publisher and subscriber. So I need to choose one. In a world where people edit their proto files from time to time, this is a very realistic situation.

The reason of this code is to address the fact, that typename and descriptor are not atomic, i.e. there may be different combinations that I must choose from.

Of course, if you make the encoding + name atomic again, you can simply store the entire info struct. It may contain redundant information, but those also don't hurt.

2023-10-30 14:17 UTC, KerstinKeller commented
Ok, yes, it's incorrect to "just" use the type, when you need to consider `encoding`+`type`, but however, in I guess all our scenarios it would have behaved the same.
Nevertheless, if we consider now SDataTypeInformation to be atomic (unlike previous `type` and `descriptor`) we should be able to simplify the whole logic?

E.g. only store the Datatypinfo (with the quality bit), and update the whole thing if a higher quality is available?
Which brings us back to a point which I would like to adress for a while.

The "name" is not the best thing to connect the topicInfo to. Better would be to connect it to Publisher / Subscriber Ids.
We can then have different "channels" in the measurement, take care of that for replay, etc.

But that would require at least the same amount of work like introducing SDataTypeInformation.

2023-11-01 11:11 UTC, closed without merging

2023-11-01 11:11 UTC, KerstinKeller commented
I will make a new PR which needs to be merged before this one.