Get mma linux more generic
eclipse-ecal/ecal pull request #1284
Opened 2023-12-18 08:51 UTC by jheeks

### Description

* remove dependency to sysstat and iostat
* get most data from /proc
* consider all mounted disks
* results in better support of embedded devices

### Related issues

- 

### Cherry-pick to

2023-12-20 10:49 UTC, hannemn commented on contrib/mma/src/linux/mma_linux.cpp
> +  page_size(sysconf(_SC_PAGE_SIZE)),
Please mark member variables with a '_' suffix like `page_size_ `.

2023-12-20 10:49 UTC, hannemn commented on contrib/mma/src/linux/mma_linux.cpp
> +  ticks_per_second(sysconf(_SC_CLK_TCK)),
Same here

2023-12-20 10:53 UTC, hannemn requested changes
Thanks for reworking the MMA and for getting rid of sysstat and ifstat dependencies. I just did a quick test on my x86 machine and everything still works as expected. Once the coding style findings are reworked, we can bring your adaptions into the master.

2023-12-20 11:00 UTC, hannemn commented on contrib/mma/src/linux/mma_linux.cpp
> +    for (auto it = proc_prev_map.begin(), next = it; it != proc_prev_map.end(); it = next)
Iterating on a map and at the same time removing certain elements can be dangerous. I am not 100% sure if your code can lead to unintended side-effects.

2023-12-20 12:35 UTC, jheeks commented on contrib/mma/src/linux/mma_linux.cpp
> +    for (auto it = proc_prev_map.begin(), next = it; it != proc_prev_map.end(); it = next)
The implementation follows a pattern given on Stackoverflow here: https://stackoverflow.com/a/39719450
The idea is to get the *next* iterator already before erasing the current entry.
The erased entries belong to old processes which are finished, means not listed in `/proc/[pid]` any more.

2023-12-20 12:42 UTC, jheeks commented on contrib/mma/src/linux/mma_linux.cpp
> +  ticks_per_second(sysconf(_SC_CLK_TCK)),
This rule applies to the already available member `mutex` as well, correct?

2023-12-22 07:57 UTC, hannemn commented on contrib/mma/src/linux/mma_linux.cpp
> +  ticks_per_second(sysconf(_SC_CLK_TCK)),
Yes, we were a bit careless with our naming conventions in the past. ;-)

2023-12-22 08:05 UTC, hannemn commented on contrib/mma/src/linux/mma_linux.cpp
> +    for (auto it = proc_prev_map.begin(), next = it; it != proc_prev_map.end(); it = next)
I see and acually thought there is a std::erase_if() functionality from the <algorithm> library available that can be used here. But it turned out this helper method comes along with C++20 which is too "new" for our code base.

2023-12-22 10:53 UTC, hannemn approved these changes

2023-12-22 10:57 UTC, merged

2024-01-02 11:38 UTC, DownerCase commented
> * consider all mounted disks

Thank you this specific change! I was recording to a "data drive" and was sad when mma wasn't reporting the usage of my recording drive..