Feature/dependency providers
eclipse-ecal/ecal pull request #1501
Opened 2024-04-04 11:05 UTC by KerstinKeller

### Description
Provide dependencies to eCAL build by dependency providers.

2024-04-04 19:01 UTC, DownerCase commented
I like the look of this! Will make it much easier on the vcpkg side 😄 What version are you targeting this for? Post 5.13?

2024-04-05 07:50 UTC, FlorianReimold commented
@DownerCase As the 5.13 branch has been created, this will become a post 5.13 feature (i.e. 6.0 or 5.14, if there will be one)

2024-04-05 10:54 UTC, FlorianReimold requested changes

2024-04-05 11:57 UTC, FlorianReimold approved these changes

2024-04-05 13:03 UTC, merged