[Python] Added BinarySubscriber and BinaryPublisher with examples
eclipse-ecal/ecal pull request #1526
Opened 2024-04-12 10:32 UTC by LeonHosch

### Description
I added a BinarySubscriber and a BinaryPublisher class to the Python wheel. Now you can send binary data using Python

### Related issues

- 

### Cherry-pick to

2024-04-12 13:28 UTC, hannemn commented on samples/python/pubsub/binary/binary_rec/CMakeLists.txt
> +set(PROJECT_GROUP minimal)
PROJECT_GROUP should be "binary" here

2024-04-12 13:35 UTC, hannemn commented on samples/python/pubsub/binary/binary_rec/binary_rec.py
> +      print("Received:  {} ms   {}".format(time, msg))
Embedding the binary into a regular doesn't look very pretty as non-printable characters will be escaped with leading backslashes which make it looks kind of messy . Maybe a hexadecimal representation would be better here such as "FF EE CC 1A".

2024-04-12 13:35 UTC, hannemn commented on samples/python/pubsub/binary/binary_rec_cb/CMakeLists.txt
> +set(PROJECT_GROUP minimal)
PROJECT_GROUP is wrong

2024-04-12 13:35 UTC, hannemn commented on samples/python/pubsub/binary/binary_rec_cb/binary_rec_cb.py
> +  print("Received:  {} ms   {}".format(time, msg))
Same here with embedded binary data.

2024-04-12 13:36 UTC, hannemn commented on samples/python/pubsub/binary/binary_snd/CMakeLists.txt
> +set(PROJECT_GROUP minimal)
wrong PROJECT_GROUP

2024-04-12 13:37 UTC, hannemn commented on samples/python/pubsub/binary/binary_snd/binary_snd.py
> +    pub.send(msg)
The first send iteration should already contain the random binary array.

2024-04-12 13:38 UTC, hannemn requested changes
See comments, I attached to the source files.

2024-04-30 08:33 UTC, FlorianReimold approved these changes

2024-04-30 08:35 UTC, merged