feature/chained pubsub
eclipse-ecal/ecal pull request #1798
Opened 2024-11-14 16:45 UTC by rex-schilasky

### Description
Added pubsub unit test to test publishing inside a subscriber callback.

2024-11-19 12:08 UTC, KerstinKeller requested changes

2024-11-19 12:08 UTC, KerstinKeller commented on ecal/tests/cpp/pubsub_test/src/pubsub_connection_test.cpp
> +  while (subscriber2_received_count < message_count)
This thread will loop forever, if not all messages were received.

2024-11-19 12:08 UTC, KerstinKeller commented on ecal/tests/cpp/pubsub_test/src/pubsub_connection_test.cpp
> +  auto publisher1_thread = [&]() {
Maybe rename variable (publisher function) and capture only neccesary variables.

2024-11-19 12:08 UTC, KerstinKeller commented on ecal/tests/cpp/pubsub_test/src/pubsub_connection_test.cpp
> +  auto subscriber1_callback = [&](const char* /*topic_name*/, const eCAL::SReceiveCallbackData* data) {
capture only necessary info (publisher)

2024-11-20 09:23 UTC, KerstinKeller commented on ecal/tests/cpp/pubsub_test/src/pubsub_connection_test.cpp
> +  {
Can you please explain the logic here?

2024-11-20 09:37 UTC, rex-schilasky commented on ecal/tests/cpp/pubsub_test/src/pubsub_connection_test.cpp
> +  {
That loop will run approx. 1 second at maximum (or if all messages sent by by pub2 are received).

2024-11-20 09:40 UTC, rex-schilasky commented on ecal/tests/cpp/pubsub_test/src/pubsub_connection_test.cpp
> +  {
Oh sorry, I see the problem. Fixed it.

2024-11-20 10:56 UTC, KerstinKeller approved these changes

2024-11-20 10:58 UTC, merged