Support one file per topic feature
eclipse-ecal/ecal pull request #755
Opened 2022-08-10 11:48 UTC by bkhalifaconti

Please check the type of change your PR introduces:
- [ ] Feature

**What is the current behavior?**

Currently all topics are written to one HDF5 file. 

Issue Number: 543

**What is the new behavior?**

- User can choose to seperate different topics in different files. A file per each topic

**Does this introduce a breaking change?**

- [ ] No

2022-08-12 11:57 UTC, FlorianReimold requested changes

2022-08-12 11:57 UTC, FlorianReimold commented on testing/contrib/ecalhdf5/hdf5_test/src/hdf5_test.cpp
> +  const std::string t3_name          = " ASCII and beyond!\a\b\t\n\v\f\r\"#$%&\'()*+,-./0123456789:;<=>\?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~������������������";
Looks like the encoding of this file broke

2022-08-12 13:21 UTC, bkhalifaconti commented on testing/contrib/ecalhdf5/hdf5_test/src/hdf5_test.cpp
> +  const std::string t3_name          = " ASCII and beyond!\a\b\t\n\v\f\r\"#$%&\'()*+,-./0123456789:;<=>\?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~������������������";
Not sure what happened to miss up with encoding, I checked encoding in my editor and it is UTF-8, I think that is correct? 
anyway I retrieved back the umlaut characters and pushed the code

2022-08-15 07:35 UTC, FlorianReimold commented
@bkhalifaconti: The following checkbox fails to update, when I load a config:
![image](https://user-images.githubusercontent.com/11774314/184594251-a4271eaf-5368-43ac-bf8d-2f51ea5ef3bb.png)

Even though this is probably a bug I introduced myself, can you fix it? I think you will have to connect to a signal emitted by `QEcalRec` and update the checkbox accoringly.

Also it looks like there is a merge conflict, as the proto files haven been moved to: `app\app_pb\src\ecal\app\pb\rec`. Please merge the master in your branch and try to fix the merge conflict

2022-08-15 09:08 UTC, bkhalifaconti commented
I merged master into my branch and pushed it, but didn't see any merge conflicts, anyway commit is pushed so you can have a look.

2022-08-15 09:38 UTC, FlorianReimold commented
> @FlorianReimold I merged master into my branch and pushed it, but didn't see any merge conflicts, anyway commit is pushed so you can have a look.

you probably merged the master of your fork into that branch. You will have to sync the master of your fork with the eclipse-ecal master before doing that. There should be a button in the web interface of your forked master to sync it to the upstream.

2022-08-15 09:55 UTC, FlorianReimold commented
I noticed another small bug (also introduced by me 😳)

the ecal_recorder_client_service_gui (from the service samples) doesn't activate / deactivate the input for 1-file-per-topic properly. Also the Tab order (when pressing the TAB key on your keyboard) is not correct. And the function is totally un-implemented 😀

![image](https://user-images.githubusercontent.com/11774314/184615246-7f16f487-cf21-4eb2-854f-23138c1fe9d4.png)

Activating and de-activating the fields is done from the qt designer_
![image](https://user-images.githubusercontent.com/11774314/184615183-7e4d1567-cd96-4273-aece-5105e9fb608c.png)

Tab order is also done from the qt designer:
![image](https://user-images.githubusercontent.com/11774314/184615215-b6db3887-c442-4f1c-bb73-e600578d4ed0.png)

2022-08-15 11:11 UTC, bkhalifaconti commented
> app\app_pb\src\ecal\app\pb\rec

@FlorianReimold  I synced master with my fork and merged still merge took place smoothly, anyway again the new merge is pushed

2022-08-17 13:57 UTC, bkhalifaconti commented
> @bkhalifaconti: The following checkbox fails to update, when I load a config: ![image](https://user-images.githubusercontent.com/11774314/184594251-a4271eaf-5368-43ac-bf8d-2f51ea5ef3bb.png)
> 
> Even though this is probably a bug I introduced myself, can you fix it? I think you will have to connect to a signal emitted by `QEcalRec` and update the checkbox accoringly.
> 
> Also it looks like there is a merge conflict, as the proto files haven been moved to: `app\app_pb\src\ecal\app\pb\rec`. Please merge the master in your branch and try to fix the merge conflict

Checkbox issue fixed. Not only signal needed to be connected but also the signal wasn't emitted properly and the loaded config wasn't applied correctly.

2022-08-18 08:51 UTC, FlorianReimold commented
@bkhalifaconti: So this PR is ready for review? 👍

2022-08-18 08:54 UTC, bkhalifaconti commented
> @bkhalifaconti: So this PR is ready for review? 👍

Not yet, there are still the last to items you mentioned. I am looking on them now

2022-09-09 10:29 UTC, merged