Fixed internal CMemoryFile structure compatibility
eclipse-ecal/ecal pull request #756
Opened 2022-08-10 14:12 UTC by hannemn

**Pull request type**

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

**What is the current behavior?**

Issue Number: N/A

**What is the new behavior?**

-
-
-

**Does this introduce a breaking change?**

- [ ] Yes
- [ ] No

**Other information**

2022-08-10 14:31 UTC, hannemn commented on ecal/core/src/io/ecal_memfile.cpp
> +      if (!memfile::db::AddFile(name_, create_, len_ + m_header.int_hdr_size, m_memfile_info))
I think the compatibility problem can still occur if create_ = false. Since the memory file is always mapped with len_ + sizeof(SInternalHeader), which may be the wrong length if the file already exists. (In the worst case the end of the memory file gets just truncated).

2022-08-10 15:45 UTC, FlorianReimold requested changes

2022-08-10 15:45 UTC, FlorianReimold commented on ecal/core/src/io/ecal_memfile.cpp
> +      if (!memfile::db::AddFile(name_, create_, len_ + m_header.int_hdr_size, m_memfile_info))
Obviously, eCAL must check the content of a memory file, if it exists. For that you have to:

- read the header size
- zero-memory a header struct
- copy min(sizeof(header), header_size_from_memfile) bytes into the created header struct

2022-08-22 11:52 UTC, FlorianReimold commented on ecal/core/src/io/ecal_memfile.h
> +      std::uint8_t  __reserved_0[6];              // Add 6 bytes padding for 8 bytes alignment on 64-bit Linux
Apparently this is a valid warning.

> The C standard additionally reserves names beginning with a double underscore, while the C++ standard strengthens this to reserve names with a double underscore occurring anywhere.
>
> Violating the naming rules above results in undefined behavior.

https://releases.llvm.org/13.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/bugprone-reserved-identifier.html

2022-08-22 12:24 UTC, hannemn commented on ecal/core/src/io/ecal_memfile.h
> +      std::uint8_t  __reserved_0[6];              // Add 6 bytes padding for 8 bytes alignment on 64-bit Linux
To be honest I don't know if this is really a good idea to use an std::array instead of c-style array in that case. Does the c++ standard guarantee that a c++ array like std::array<std::uint8_t, x> foo occupies x bytes in the memory layout like std::uint8_t foo[x]?

2022-08-23 13:53 UTC, FlorianReimold requested changes

2022-08-23 13:53 UTC, FlorianReimold commented on ecal/core/src/io/ecal_memfile.h
> +      std::array<std::uint8_t, 2> _reserved_0;       // Add 2 bytes padding for 4 bytes alignment on Windows
Those should be initialized to 0 as well. While this is not relevant now, this may be relevant when we later use one of those fields. Then the legacy applications should always send a 0 there to not confuse newer applications that read an actual value from those fields.

```suggestion
      std::array<std::uint8_t, 2> _reserved_0 = {};       // Add 2 bytes padding for 4 bytes alignment on Windows  
```

2022-08-23 13:53 UTC, FlorianReimold commented on ecal/core/src/io/ecal_memfile.h
> +      std::array<std::uint8_t, 6> _reserved_0;       // Add 6 bytes padding for 8 bytes alignment on 64-bit Linux
```suggestion
      std::array<std::uint8_t, 6> _reserved_0 = {};       // Add 6 bytes padding for 8 bytes alignment on 64-bit Linux
```

2022-08-23 13:53 UTC, FlorianReimold commented on ecal/core/src/io/ecal_memfile.h
> +      // std::array<std::uint8_t, 7>  _reserved_1;
```suggestion
      // std::array<std::uint8_t, 7>  _reserved_1 = {};
```

2022-08-23 14:48 UTC, hannemn commented on ecal/core/src/io/ecal_memfile.h
> +      std::array<std::uint8_t, 2> _reserved_0;       // Add 2 bytes padding for 4 bytes alignment on Windows
In case of _reserved_0 i don't think that it is necessary to zero the memory, since the field will never be used for future applications and is only intended to be compatible to the padding of the previous header layout (which maybe already contains non-zero values).

In the next version of the header I will introduce an additional version field to query which fields or rather features are available for the memory file. Then it can be easily extended for future use cases.

2022-08-24 06:50 UTC, FlorianReimold commented on ecal/core/src/io/ecal_memfile.h
> +      std::array<std::uint8_t, 2> _reserved_0;       // Add 2 bytes padding for 4 bytes alignment on Windows
Hm, OK, but it still feels wrong (to me) to write uninitialized memory to a file. But should be OK, if you prefer it like that.

2022-08-24 07:45 UTC, hannemn commented on ecal/core/src/io/ecal_memfile.h
> +      std::array<std::uint8_t, 2> _reserved_0;       // Add 2 bytes padding for 4 bytes alignment on Windows
I can change it if you feel better with zeros in the reserved field. The overhead of initialization should be acceptable. ;-)

2022-08-24 10:06 UTC, FlorianReimold approved these changes

2022-08-24 10:18 UTC, merged