shm handshake timeout CPublisher API (fixing issue #875)
eclipse-ecal/ecal pull request #876
Opened 2022-11-15 07:52 UTC by rex-schilasky

**Pull request type**

Provide new shm handshake timeout API for the `CPublisher`.

Please check the type of change your PR introduces:
- [X] Feature

Issue Number: #875

2022-11-15 11:07 UTC, FlorianReimold requested changes

2022-11-15 11:07 UTC, FlorianReimold commented on ecal/core/src/io/ecal_memfile_header.h
> +    uint64_t   ack_timout = 0;
please add the unit (probably milliseconds) to avoid confusion

2022-11-15 11:07 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_writer.cpp
> +        wdata.acknowledge_timeout = m_acknowledge_timeout;
please add the unit (probably milliseconds)  to the variable name to avoid confusion

2022-11-15 11:07 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_writer.h
> +    long               m_acknowledge_timeout;
please add the unit (probably milliseconds)  to the variable name to avoid confusion. This may even be a properly typed chrono time object

2022-11-15 11:07 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_writer_data.h
> +    long         acknowledge_timeout = 0;
please add the unit (probably milliseconds)  to the variable name to avoid confusion. This may even be a properly typed chrono time object, if the struct will never be used in C

2022-11-15 11:07 UTC, FlorianReimold commented on ecal/core/include/ecal/ecal_publisher.h
> +    bool ShmSetAcknowledgeTimeout(int acknowledge_timeout_ms_);
Maybe it would be better to accept an std::chrono::milliseconds here, if possible

2022-11-15 11:59 UTC, KerstinKeller commented
@rex-schilasky the compatibility with old subscribers / new publishers works only in "handshake off" mode, correct?

2022-11-15 12:13 UTC, rex-schilasky commented
> @rex-schilasky the compatibility with old subscribers / new publishers works only in "handshake off" mode, correct?

1. New publisher / old subscriber
- if only ecal.ini is used: full compatibility
- if publisher uses API to switch handshake OFF it will be OFF
- if publisher uses API to switch handshake ON and ecal.ini defines OFF it will be OFF

2. Old publisher / new subscriber
- Feature is always OFF (new subscriber is no more using ecal.ini settings)

2022-11-15 14:46 UTC, KerstinKeller commented
I think we do not have to care 100% about the compatibility part. More important is that it will work 100% if all eCAL participants use eCAL 5.11.

2022-12-05 08:37 UTC, hannemn commented on ecal/core/include/ecal/ecal_publisher.h
> +    bool ShmSetAcknowledgeTimeout(std::chrono::duration<Rep, Period> acknowledge_timeout_)
Of course this is the proper way to define durations in C++, but for all other public API functions in eCAL we just use a simple 64 bit integer. For consistency reasons we should maybe keep it similiar to the other function signatures.

2022-12-05 12:43 UTC, merged