Replaced internal Udpcap with a submodule
eclipse-ecal/ecal pull request #884
Opened 2022-11-22 16:05 UTC by FlorianReimold

The new Udpcap can be found here:
https://github.com/eclipse-ecal/udpcap

2022-11-24 13:58 UTC, hannemn requested changes
The rest looks fine for me.

2022-11-24 13:58 UTC, hannemn commented on CMakeLists.txt
> +option(ECAL_THIRDPARTY_BUILD_UDPCAP            "Build udpap library with eCAL"                                    OFF)
```suggestion
option(ECAL_THIRDPARTY_BUILD_UDPCAP            "Build udpcap library with eCAL"                                    OFF)
```
typo ;-)

2022-11-24 14:27 UTC, KerstinKeller reviewed
In general I approve, but let's dicuss first if we need to change target names for pcapplusplus and npcap before pulling in this version.

2022-11-25 14:54 UTC, KerstinKeller approved these changes

2022-11-25 15:20 UTC, merged