Feature/#873 topic2mcast
eclipse-ecal/ecal pull request #950
Opened 2023-01-24 16:40 UTC by KerstinKeller

**Pull request type**
- [x] Feature

**What is the current behavior?**
Unintuitive masking for multicast addresses

Issue Number: #873

**What is the new behavior?**
This PR introduces a new multicast configuration version mode, e.g. V2. The previous mode is called V1.
V1 stays the standard mode for now, to be compatible with older eCAL Versions. 
V2 is introduced, and allows better configuration.

Please review:
The behavior to treat collisions:
Per default, `multicast_group` is the MC address to send registration information on.
If a topic is to be sent on the same MC address as registration information, it is send on +1. If this causes "overflow" (e.g. multicast group `139.0.0.255` and mask of `255.255.255.0`, the topic will be sent on `139.0.0.0`.
It is to be discussed if this is a favorable behavior.

The behavior is now somewhat documented in the ini file, it should probably be documented extensively in the documentation.

**Does this introduce a breaking change?**
- [x] No

It's not a breaking change as the default configuration stays as is.

2023-01-25 13:11 UTC, hannemn requested changes

2023-01-25 13:11 UTC, hannemn commented on ecal/core/include/ecal/ecal_config.h
> +    enum class UDPConfigVersion
Naming this enum to` UdpMulticastConfigVersion` would better match to the according getter function `GetUdpMulticastConfigVersion`.

2023-01-25 13:11 UTC, hannemn commented on ecal/core/src/io/udp_configurations.cpp
> +std::string eCAL::UDP::GetLoggingMulticastAdress()
Typo Ad**d**ress

2023-01-25 13:11 UTC, hannemn commented on ecal/core/src/io/udp_configurations.cpp
> +std::string eCAL::UDP::GetRegistrationMulticastAdress()
Typo Ad**d**ress

2023-01-25 13:11 UTC, hannemn commented on ecal/core/src/io/udp_configurations.cpp
> +std::string eCAL::UDP::GetTopicMulticastAdress(const std::string& topic_name)
Typo Ad**d**ress

2023-01-25 13:39 UTC, KerstinKeller commented on ecal/core/src/io/udp_configurations.cpp
> +std::string eCAL::UDP::GetRegistrationMulticastAdress()
should I also rename the namespace `UDP` -> `Udp` ?

2023-01-25 13:58 UTC, FlorianReimold commented on ecal/core/src/io/udp_configurations.cpp
> +std::string eCAL::UDP::GetRegistrationMulticastAdress()
Would that change some public API?

If not, I usually prefer CamelCase where abbreviations are treated as words. So yes, I would have made it `Udp`. If incorporated in longer variable names, this makes it easier to distinguish between the components (e.g. `UDPSocket` vs `UdpSocket`, or `TCPIPConnection` vs `TcpIpConnection`). But in the end it doesn't really matter.

2023-01-25 14:04 UTC, FlorianReimold commented on ecal/core/include/ecal/ecal_config.h
> +    enum class UDPConfigVersion
I agree

2023-01-25 16:15 UTC, KerstinKeller commented on ecal/core/src/io/udp_configurations.cpp
> +std::string eCAL::UDP::GetRegistrationMulticastAdress()
No, no public API, I just introduced some namespacing.
Here we separate by `::` so it's not so much of an issue. but I mean `UDP` it's an abbreviation...
I'll just keep it. (we also have namespace `eCAL` not `Ecal`).

2023-01-26 15:41 UTC, FlorianReimold requested changes

2023-01-26 15:45 UTC, KerstinKeller commented on doc/rst/configuration/options.rst
> +   ``255.0.0.0``-``255.255.255.255``
we have no verifaction of any inputs whatsoever in the ini files. neither for this entry nor for any of the others.
I would tackle this separately.

2023-01-26 15:45 UTC, KerstinKeller commented on doc/rst/configuration/options.rst
> +   With ``multicast_group``: ``239.0.0.1`` and ``multicast_mask``: ``255.255.255.255``, topic traffic will be sent on addresses ``239.0.0.0``-``239.0.0.255``.
you are correct

2023-01-26 15:46 UTC, KerstinKeller commented on ecal/core/include/ecal/ecal_config.h
> +#pragma once
yes, it was actually missing! An I got multiple definition erros due to defining a class enum in the header.
Apparently it's not a problem for function definitions.

2023-01-27 09:03 UTC, FlorianReimold approved these changes

2023-01-27 10:00 UTC, merged